<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\controllers\base;
use Yii;
use app\models\ProfilDesa;
    use app\models\search\ProfilDesaSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
use app\models\Action;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
* ProfilDesaController implements the CRUD actions for ProfilDesa model.
*/
class ProfilDesaController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;
public function behaviors()
{
//NodeLogger::sendLog(Action::getAccess($this->id));
//apply role_action table for privilege (doesn't apply to super admin)
return Action::getAccess($this->id);
}

/**
* Lists all ProfilDesa models.
* @return mixed
*/
public function actionIndex()
{
    $model = ProfilDesa::find()->all();
    $searchModel  = new ProfilDesaSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

if($model == null){
    return $this->render('index', [
    'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}else{
    return $this->redirect(['view', 'id' => $model[0]["id"]]);
}
}

/**
* Displays a single ProfilDesa model.
* @param integer $id
*
* @return mixed
*/
public function actionView($id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($id),
]);
}

/**
* Creates a new ProfilDesa model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new ProfilDesa;

try {
if ($model->load($_POST)) {
    $logos = UploadedFile::getInstance($model, 'logo');
        if($logos !=NULL){
                    # store the source logos name
                    $model->logo = $logos->name;
                    $arr = explode(".", $logos->name);
                    $extension = end($arr);

                    # generate a unique logos name
                    $model->logo = Yii::$app->security->generateRandomString() . ".{$extension}";

                    # the path to save logos
                    // unlink(Yii::getAlias("@app/web/uploads/pengajuan/") . $oldFile);
                    if(file_exists(Yii::getAlias("@app/web/uploads/profil_desa/logo/")) == false){
                        mkdir(Yii::getAlias("@app/web/uploads/profil_desa/logo/"), 0777, true);
                    }
                    $path = Yii::getAlias("@app/web/uploads/profil_desa/logo/") . $model->logo;
        $logos->saveAs($path);
                }
if($model->save()){
    return $this->redirect(['view', 'id' => $model->id]);
}
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing ProfilDesa model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id
* @return mixed
*/
public function actionUpdate($id)
{
$model = $this->findModel($id);
$oldFoto=$model->logo;
if ($model->load($_POST)) {
    $logos = UploadedFile::getInstance($model, 'logo');
            if ($logos != NULL) {
                # store the source file name
                $model->logo = $logos->name;
                $arr = explode(".", $logos->name);
                $extension = end($arr);

                # generate a unique file name
                $model->logo = Yii::$app->security->generateRandomString() . ".{$extension}";

                # the path to save file
                if(file_exists(Yii::getAlias("@app/web/uploads/profil_desa/logo/")) == false){
                    mkdir(Yii::getAlias("@app/web/uploads/profil_desa/logo/"), 0777, true);
                }
                $path = Yii::getAlias("@app/web/uploads/profil_desa/logo/") . $model->logo;
                if($oldFoto != NULL){

                    $logos->saveAs($path);
                    unlink(Yii::$app->basePath . '/web/uploads/profil_desa/logo/' . $oldFoto);
                }else{
                    $logos->saveAs($path);
                }
            }else{
                $model->logo = $oldFoto;
            }
            
if($model->save()){
    return $this->redirect(['view', 'id' => $model->id]);
}
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing ProfilDesa model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $id
* @return mixed
*/
public function actionDelete($id)
{
try {
$this->findModel($id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the ProfilDesa model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $id
* @return ProfilDesa the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($id)
{
if (($model = ProfilDesa::findOne($id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
