<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
/**
 * This is the base-model class for table "demografi".
 *
 * @property integer $id
 * @property string $foto
 * @property string $isi_demografi
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Demografi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'demografi';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['isi_demografi'], 'required'],
            [['isi_demografi'], 'string'],
            [['foto'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'foto' => 'Foto',
            'isi_demografi' => 'Isi Demografi',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
