<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
/**
 * This is the base-model class for table "galeri".
 *
 * @property integer $id
 * @property string $judul
 * @property string $gambar
 * @property integer $deleted_status
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Galeri extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'galeri';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul', 'gambar', 'deleted_status'], 'required'],
            [['deleted_status'], 'integer'],
            [['judul', 'gambar'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'judul' => 'Judul',
            'gambar' => 'Gambar',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_status' => 'Deleted Status',
        ];
    }




}
