<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
/**
 * This is the base-model class for table "profil_desa".
 *
 * @property integer $id
 * @property string $nama_desa
 * @property string $alamat
 * @property string $nomor_telepon
 * @property string $logo
 * @property string $visi_misi
 * @property string $sejarah
 * @property string $instagram
 * @property string $facebook
 * @property double $latitude
 * @property double $longitude
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class ProfilDesa extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'profil_desa';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_desa', 'alamat', 'nomor_telepon'], 'required'],
            [['alamat', 'visi_misi', 'sejarah'], 'string'],
            [['latitude', 'longitude'], 'number'],
            [['nama_desa', 'logo', 'instagram', 'facebook'], 'string', 'max' => 255],
            [['nomor_telepon'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_desa' => 'Nama Desa',
            'alamat' => 'Alamat',
            'nomor_telepon' => 'Nomor Telepon',
            'logo' => 'Logo',
            'visi_misi' => 'Visi Misi',
            'sejarah' => 'Sejarah',
            'instagram' => 'Instagram',
            'facebook' => 'Facebook',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
