<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $name
 * @property string $no_hp
 * @property string $nik
 * @property string $alamat
 * @property string $ttd_digital
 * @property integer $role_id
 * @property string $photo_url
 * @property string $last_login
 * @property string $last_logout
 *
 * @property \app\models\PendaftaranUsaha[] $pendaftaranUsahas
 * @property \app\models\Role $role
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password', 'name','nik', 'role_id'], 'required'],
            [['alamat'], 'string'],
            [['role_id'], 'integer'],
            [['last_login', 'last_logout'], 'safe'],
            [['nip'], 'string', 'max' => 25],
            [['username', 'password', 'name'], 'string', 'max' => 50],
            [['no_hp'], 'string', 'max' => 20],
            [['nik', 'ttd_digital', 'photo_url'], 'string', 'max' => 255],
            ['email', 'email'],
            [['username'], 'unique'],
            [['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Role::className(), 'targetAttribute' => ['role_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'name' => 'Name',
            'email' => 'Email',
            'no_hp' => 'No Hp',
            'nik' => 'Nik',
            'alamat' => 'Alamat',
            'ttd_digital' => 'Ttd Digital',
            'role_id' => 'Role',
            'nip' => 'NIP',
            'photo_url' => 'Photo Url',
            'last_login' => 'Last Login',
            'last_logout' => 'Last Logout',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendaftaranUsahas()
    {
        return $this->hasMany(\app\models\PendaftaranUsaha::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(\app\models\Role::className(), ['id' => 'role_id']);
    }




}
