<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "view_perangkat_desa".
 *
 * @property integer $id
 * @property string $foto_1
 * @property string $foto_2
 * @property string $isi_perangkat_desa
 * @property string $aliasModel
 */
abstract class ViewPerangkatDesa extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'view_perangkat_desa';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['isi_perangkat_desa'], 'string'],
            [['foto_1', 'foto_2'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'foto_1' => 'Foto 1',
            'foto_2' => 'Foto 2',
            'isi_perangkat_desa' => 'Isi Perangkat Desa',
        ];
    }




}
