<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\date\DatePicker;
use kartik\file\FileInput;
/**
* @var yii\web\View $this
* @var app\models\PerangkatDesa $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
        'id' => 'PerangkatDesa',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
        );
        ?>
			<?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'alamat')->textarea(['rows' => 6]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'jabatan')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Jabatan::find()->all(), 'id', 'nama_jabatan'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['jabatan'])),
    ]
); ?>
            <?=$form->field($model, 'tanggal_lahir')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Pilih Tanggal Lahir'],
                'readonly' => true,
                'pluginOptions' => [
                    'format' => 'yyyy-m-d',
                    'autocomplete' => "off",
                    'autoclose'=>true,
                ],
            ]);?>
            <?=$form->field($model, 'tanggal_mulai_tugas')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Pilih Tanggal Mulai Tugas'],
                'readonly' => true,
                'pluginOptions' => [
                    'format' => 'yyyy-m-d',
                    'autocomplete' => "off",
                    'autoclose'=>true,
                ],
            ]);?>
			<?= $form->field($model, 'sk_pengangkatan')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'foto',[
                    
                    'options' => ['tag' => false]])->widget(FileInput::classname(), [
                'options' => ['accept' => 'file/*'],
                'pluginOptions' => [
                    'allowedFileExtensions' => ['png','jpg','jpeg'],
                    'maxFileSize' => 6500,
                    'showRemove' => false,
                    'showUpload' => false,
                    'showCaption' => false,
                    'dropZoneEnabled' => false,
                    'browseLabel' => 'Upload File',
                ],
            ]);?> 
            <?php
                        if($model->foto != null){
                            ?>
                            <div class="form-group">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <?= Html::img(\Yii::$app->request->BaseUrl.'/uploads/perangkat_desa/foto/'.$model->foto,['width'=>100]); ?>
                                </div>
                            </div>
                            <?php
                        }
                        ?>       <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?=  Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?=  Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>