<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\search\PerangkatDesaSearch $searchModel
*/

$this->title = 'Perangkat Desa';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
</p>


    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

    <div class="box box-info">
        <div class="box-body">
            <div class="table-responsive">
                <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager'        => [
                'class'          => yii\widgets\LinkPager::className(),
                'firstPageLabel' => 'First',
                'lastPageLabel'  => 'Last'                ],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class'=>'x'],
                'columns' => [

                \app\components\ActionButton::getButtons(),

			'nama',
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'jabatan',
    'value' => function ($model) {
        if ($rel = $model->jabatans) {
            return $rel->nama_jabatan;
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
            [
                'class' => yii\grid\DataColumn::className(),
                'attribute'=>'tanggal_lahir',
                'format' => 'raw',
                'value'=>function($model){
                    return \app\components\Tanggal::toReadableDate($model->tanggal_lahir);
                }
            ],
            [
                'class' => yii\grid\DataColumn::className(),
                'attribute'=>'tanggal_mulai_tugas',
                'format' => 'raw',
                'value'=>function($model){
                    return \app\components\Tanggal::toReadableDate($model->tanggal_mulai_tugas);
                }
            ],
			'sk_pengangkatan',
			[
                'attribute' =>'foto',
                'format' =>'html',
                'value' =>function($model) {
                   return Html::img(\Yii::$app->request->BaseUrl.'/uploads/perangkat_desa/foto/'.$model->foto,['width'=>100]);
                 },
             ],
                ],
                ]); ?>
            </div>
        </div>
    </div>

    <?php \yii\widgets\Pjax::end() ?>

