<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Berita $model
*/

$this->title = 'Berita ' . $model->slug;
?>
<div class="giiant-crud berita-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Berita', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('app\models\Berita'); ?>

            <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                    
        'judul',
        // 'isi_berita:ntext',
        [
            'attribute' => 'isi_berita',
            'format' => 'raw'
        ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'kategori_id',
    'value' =>function($model){
        return $model->kategori->nama_kategori;
    }
],
        [
            'attribute' => 'gambar',
            'header'=> 'Download Gambar',
            'format' =>'raw',
            'value' => function($model){
                if($model->gambar != null){
                    return Html::a("<i class='fa fa-download'></i>".' Download Gambar', ["unduh-gambar", "id"=>$model->id], [
                        "class"=>"btn btn-primary",
                        "title"=>"Unduh File",
                        "data-confirm" => "Apakah Anda akan mengunduh Gambar ini ?",
                    ]);
                }else{
                    return "Belum Upload File";
                }
            }
        ],
        'slug',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'created_by',
    'value' => function($model){
        return $model->createdBy->name;
    }
],
        // 'deleted_status',
        [
            'attribute' => 'deleted_status',
            'format' => 'raw',
            'value' => function($model) {
                if ($model->deleted_status == 0) {
                    return '<span class="label label-success">Publish</span>';
                }else {
                    return '<span class="label label-danger">Non Publish</span>';
                }
            }
        ],
        
        'created_at',
        'updated_at',
            ],
            ]); ?>

            <hr/>

            <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Non Publish', ['delete', 'id' => $model->id],
            [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . 'Are you sure to delete this item?' . '',
            'data-method' => 'post',
            ]); ?>
            <?php $this->endBlock(); ?>


            
            <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->judul.'</b>',
    'content' => $this->blocks['app\models\Berita'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
